controller_list:
  - name: "/xarm/xarm7_traj_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

  - name: "/xarm/gripper_traj_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - drive_joint
